/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.ManipularImagem;
import control.Conexao;
import modelo.model;
import control.ControleCadastro;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdk.nashorn.internal.runtime.Debug.id;
/**
 *
 * @author PC_WIN10
 */
public class TelaConsulta extends javax.swing.JFrame {

       Conexao conn = new Conexao();
       ManipularImagem map = new ManipularImagem();
       ControleCadastro control = new ControleCadastro();
       model mod = new model();
       
       BufferedImage imagem;
    
    /**
     * Creates new form TelaInicial
     */
    public TelaConsulta() {
        initComponents();
        conn.getConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        janela_foto = new javax.swing.JLabel();
        Rg = new javax.swing.JLabel();
        CampoUrlFoto = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoRg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoId = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        BotaoSalvar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        upload = new javax.swing.JButton();
        BotaoPesquisar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInicial = new javax.swing.JMenu();
        TelaCadastro = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        MenuTelaConsulta = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Consulta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nome.setText("Nome:");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 80, 20));

        janela_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        janela_foto.setLabelFor(janela_foto);
        janela_foto.setToolTipText("foto");
        janela_foto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(janela_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 120));

        Rg.setText("RG:");
        getContentPane().add(Rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, 20));

        CampoUrlFoto.setEnabled(false);
        CampoUrlFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUrlFotoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoUrlFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, -1));

        foto.setText("URL FOTO");
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, 20));

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        CampoRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRgActionPerformed(evt);
            }
        });
        getContentPane().add(CampoRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 220, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESAMC");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 60));

        CampoId.setToolTipText("Id AUTO_INCLEMENT");
        CampoId.setEnabled(false);
        CampoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIdActionPerformed(evt);
            }
        });
        getContentPane().add(CampoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, -1));

        ID.setText("ID");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, 20));

        CampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 220, -1));

        Email.setText("E-mail:");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, 20));

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 80, -1));

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 70, -1));

        upload.setText("Selecionar Foto");
        upload.setEnabled(false);
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        getContentPane().add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        BotaoPesquisar.setText("Pesquisar");
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 80, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/f5.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));

        MenuInicial.setText("CADASTRO");
        MenuInicial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TelaCadastro.setText("CADASTRO");
        TelaCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaCadastroActionPerformed(evt);
            }
        });
        MenuInicial.add(TelaCadastro);

        jMenuBar1.add(MenuInicial);

        MenuConsulta.setText("CONSULTA");

        MenuTelaConsulta.setText("CONSULTA");
        MenuTelaConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuTelaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTelaConsultaActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuTelaConsulta);

        jMenuBar1.add(MenuConsulta);

        MenuSair.setText("SAIR");

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        MenuSair.add(Sair);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
     CampoRg.requestFocus();
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void CampoRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRgActionPerformed
        CampoEmail.requestFocus();
    }//GEN-LAST:event_CampoRgActionPerformed

    private void CampoUrlFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUrlFotoActionPerformed
      BotaoSalvar.requestFocus();
    }//GEN-LAST:event_CampoUrlFotoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void TelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaCadastroActionPerformed
        TelaConsulta tela = new TelaConsulta();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_TelaCadastroActionPerformed

    private void MenuTelaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTelaConsultaActionPerformed
        TelaConsulta tela = new TelaConsulta();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuTelaConsultaActionPerformed

    private void CampoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIdActionPerformed
          
    }//GEN-LAST:event_CampoIdActionPerformed
    
    private void CampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailActionPerformed
         upload.requestFocus();
    }//GEN-LAST:event_CampoEmailActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        /*
        aqui salva em uma pasta dentro do projeto!!
        
        String caminho = getClass().getResource("/imagens").toString().substring(5);
        File outputfile = new File(caminho + "imagem");
        ImageIO.write(imagem, "jpg", outputfile);
         */
        try {
            mod.setNome(CampoNome.getText());
            mod.setRg(CampoRg.getText());
            mod.setEmail(CampoEmail.getText());
            mod.setFoto(ManipularImagem.getImgBytes(imagem)); // transforma a imagem em byte para jogar no banco de dados
            control.Salvar(mod);

            JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso");
        } catch (Exception ex) {
            CampoNome.setText("");
            CampoRg.setText("");
            CampoEmail.setText("");
            CampoUrlFoto.setText("");
            janela_foto.setText("");
            CampoNome.requestFocus();
        }
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser busca_foto = new JFileChooser();
        int res = busca_foto.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = busca_foto.getSelectedFile();
            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);
                CampoUrlFoto.setText(arquivo.getPath());
                janela_foto.setIcon(new ImageIcon(imagem));

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não selecionou nunhum arquivo.");

        }                                  
    
    }//GEN-LAST:event_uploadActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        CampoId.setText("");
        CampoNome.setText("");
        CampoRg.setText("");
        CampoEmail.setText("");
        CampoUrlFoto.setText("");
        janela_foto.setText("");
        CampoNome.requestFocus();
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed
       mod.setPesquisa(CampoNome.getText());
       model model = control.Pesquisa(mod);
           //= Integer.parseInt(CampoId.getText());
           //CampoId.setText(mod.getId());
        CampoId.setText(Integer.toString(mod.getId()));
        CampoNome.setText(mod.getNome());
        CampoRg.setText(mod.getRg());
        CampoEmail.setText(mod.getEmail());
        ManipularImagem.exibiImagemLabel(mod.getFoto(), janela_foto);
         
             
     
    }//GEN-LAST:event_BotaoPesquisarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoId;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoRg;
    private javax.swing.JTextField CampoUrlFoto;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel ID;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenu MenuInicial;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem MenuTelaConsulta;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Rg;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem TelaCadastro;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel janela_foto;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
