/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.ManipularImagem;
import control.Conexao;
import modelo.model;
import control.ControleCadastro;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
/**
 *
 * @author PC_WIN10
 */
public class TelaLogin extends javax.swing.JFrame {

       Conexao conn = new Conexao();
       ManipularImagem map = new ManipularImagem();
       ControleCadastro control = new ControleCadastro();
       model mod = new model();
       
       BufferedImage imagem;
    
    /**
     * Creates new form TelaInicial
     */
    public TelaLogin() {
        initComponents();
        conn.getConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        Rg = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotaoOk = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInicial = new javax.swing.JMenu();
        TelaCadastro = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nome.setText("Login:");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 20));

        Rg.setText("Senha:");
        getContentPane().add(Rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 20));

        campoLogin.setToolTipText("Digite o nome");
        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(campoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 60));

        BotaoOk.setText("Ok");
        BotaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 80, -1));

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        campoSenha.setToolTipText("Digite a Senha");
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/f5.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));

        MenuInicial.setText("LOGIN");
        MenuInicial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TelaCadastro.setText("LOGIN");
        TelaCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaCadastroActionPerformed(evt);
            }
        });
        MenuInicial.add(TelaCadastro);

        jMenuBar1.add(MenuInicial);

        MenuSair.setText("SAIR");

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        MenuSair.add(Sair);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
     campoSenha.requestFocus();
    }//GEN-LAST:event_campoLoginActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void TelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaCadastroActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_TelaCadastroActionPerformed
    
    private void BotaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkActionPerformed
        ControleCadastro log = new ControleCadastro();
      
        if (log.checkLogin(campoLogin.getText(), campoSenha.getText())) {
            new TelaInicial().setVisible(true);
        } else {
            campoLogin.setText("");
            campoSenha.setText("");
            campoLogin.requestFocus();
        }
    }//GEN-LAST:event_BotaoOkActionPerformed
  
    
    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        campoLogin.setText("");
        campoSenha.setText("");
        campoLogin.requestFocus();
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
       BotaoOk.requestFocus();
    }//GEN-LAST:event_campoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoOk;
    private javax.swing.JMenu MenuInicial;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Rg;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem TelaCadastro;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
